name: lint

on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - run: npm run format:check

      - run: npm run lint
